/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empeño;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jorge Martinez
 */
public class FrameEmp extends javax.swing.JFrame {

    /**
     * Creates new form FrameEmp
     */
    public FrameEmp() {
        //PESTAÑA UNO
        newcliente = new cliente[20];
        numClientesIngresados = 0;
        model = new DefaultListModel();

        //PESTAÑA DOS
        String [] Categorias = {"JOYERIA","ELCTRONICO","ELECTRODOMESTICO","JUGUETE","MUEBLE"};
        modeloCategoria = new DefaultComboBoxModel(Categorias);
        ListaPrendas = new Prenda[20];
        prendasemp = new DefaultListModel();
        
        //PESTAÑA TRES
        listPrendas = new String[20];
        PrendasEmpeñadas = new DefaultComboBoxModel(listPrendas);
        prendaguardada = new CasaEmpeño[20]; 
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        PHONENUM = new javax.swing.JTextField();
        RESIDUE = new javax.swing.JTextField();
        BOTONREGISTRO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PRENDA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DAY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MONTH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        YEAR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        VALUATE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PRESTAMO = new javax.swing.JTextField();
        BOTTONPRENDA = new javax.swing.JButton();
        CATEGORIA = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LISTA2 = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DIA2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MES2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AÑO2 = new javax.swing.JTextField();
        CALCULAR = new javax.swing.JToggleButton();
        REMBOLSO = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PAGOFINAL = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        LISTA3 = new javax.swing.JList<>();
        REGISTRO3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        PRESTADO3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        DUEÑO3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Numero Telefonico:");

        jLabel4.setText("Saldo:");

        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });

        PHONENUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHONENUMActionPerformed(evt);
            }
        });

        BOTONREGISTRO.setText("Agregar");
        BOTONREGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONREGISTROActionPerformed(evt);
                actionAgregarCliente(evt);
            }
        });

        jList1.setModel(model);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PHONENUM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(RESIDUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BOTONREGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PHONENUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RESIDUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BOTONREGISTRO)
                        .addGap(0, 178, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registro", jPanel1);

        jLabel6.setText("Prenda:");

        PRENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRENDAActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        jLabel5.setText("Fecha:");

        jLabel7.setText("Día");

        jLabel8.setText("Mes");

        jLabel9.setText("Año");

        jLabel10.setText("Valor comercial ");

        jLabel11.setText("Monto a prestar:");

        PRESTAMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESTAMOActionPerformed(evt);
            }
        });

        BOTTONPRENDA.setText("OK");
        BOTTONPRENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTTONPRENDAActionPerformed(evt);
                accionPrenda(evt);
            }
        });

        CATEGORIA.setModel(modeloCategoria);
        CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATEGORIAActionPerformed(evt);
            }
        });

        LISTA2.setModel(prendasemp);
        LISTA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LISTA2(evt);
            }
        });
        jScrollPane2.setViewportView(LISTA2);

        jLabel22.setText("FECHA EN FORMATO DD/MM/AAAA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(CATEGORIA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(57, 57, 57))
                                    .addComponent(PRENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PRESTAMO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(BOTTONPRENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(VALUATE, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)))))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DAY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PRENDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(VALUATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BOTTONPRENDA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(PRESTAMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Empeño", jPanel2);

        jLabel12.setText("Prenda:");

        jLabel13.setText("Fecha:");

        jLabel14.setText("Día:");

        jLabel15.setText("Mes:");

        MES2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MES2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Año:");

        CALCULAR.setText("Calcular y Regresar prenda ");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTIONCALCULAR(evt);
            }
        });

        jLabel17.setText("PAGO");

        jLabel18.setText("Monto a pagar:");

        LISTA3.setModel(prendasemp);
        LISTA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LISTA3SELECTED(evt);
            }
        });
        jScrollPane3.setViewportView(LISTA3);

        jLabel19.setText("FECHA DE REGISTRO");

        jLabel20.setText("MONTO PRESTADO");

        PRESTADO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESTADO3ActionPerformed(evt);
            }
        });

        jLabel21.setText("DUEÑO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MES2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AÑO2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(REGISTRO3)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(PRESTADO3)
                                    .addComponent(jLabel21)
                                    .addComponent(DUEÑO3)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CALCULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(REMBOLSO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PAGOFINAL, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(DIA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(MES2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(AÑO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(2, 2, 2)
                        .addComponent(REGISTRO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PRESTADO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DUEÑO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CALCULAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(REMBOLSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(PAGOFINAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Prenda y ganancias", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRENDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRENDAActionPerformed

    private void PRESTAMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESTAMOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRESTAMOActionPerformed

    private void BOTTONPRENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTTONPRENDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTTONPRENDAActionPerformed

    private void BOTONREGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONREGISTROActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BOTONREGISTROActionPerformed

    private void actionAgregarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAgregarCliente
        // TODO add your handling code here:
        cliente clientex;
        clientex = new cliente(NAME.getText(),PHONENUM.getText(),Double.parseDouble(RESIDUE.getText()));
        clientex.setNombre(NAME.getText());
        clientex.setTelefono(PHONENUM.getText());
        clientex.setSaldo(Double.parseDouble(RESIDUE.getText()));
        model.addElement(clientex.getNombre());
        newcliente[numClientesIngresados]=clientex;
        numClientesIngresados++;
    }//GEN-LAST:event_actionAgregarCliente

    private void accionPrenda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionPrenda
        // TODO add your handling code here:
        Prenda prendax;
        String fecha = DAY.getText().toString() +" "+ MONTH.getText().toString() +" "+ YEAR.getText().toString();
        prendax = new Prenda(PRENDA.getText(), CATEGORIA.getSelectedItem().toString(), fecha, Double.parseDouble(VALUATE.getText()));
        prendax.setCategoria(CATEGORIA.getSelectedItem().toString());
        prendax.setFecha(fecha);
        prendax.setPrenda(PRENDA.getText());
        prendax.setValorComercial(Integer.parseInt(VALUATE.getText()));
        prendax.setPrestamo(Integer.parseInt(VALUATE.getText()));
        prendasemp.addElement(prendax.getPrenda());
        //listPrendas[numClientesIngresados] = prendax.getPrenda();
        ListaPrendas[numPrendas]=prendax;
        PRESTAMO.setText(String.valueOf(prendax.getPrestamo()));
        
        //prendax.setPrestamo(Double.parseDouble(PRESTAMO.getText()));
        numPrendas++;
    }//GEN-LAST:event_accionPrenda

    private void MES2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MES2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MES2ActionPerformed

    private void CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATEGORIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATEGORIAActionPerformed

    private void ACTIONCALCULAR(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTIONCALCULAR
        // TODO add your handling code here: 
        CasaEmpeño prendax;
        prendax = new CasaEmpeño();
        prendax.setPagofinal(Double.parseDouble(PRESTADO3.getText()));
        double adicion20 = (Double.parseDouble(PRESTADO3.getText())*.40);
        adicion20 = adicion20 / 0.60;
        adicion20 = Double.parseDouble(PRESTADO3.getText())+adicion20;
        adicion20 = adicion20 * .20;
        prendax.setPagofinal(adicion20);
        prendaguardada[numeroPrendas]=prendax;
        
        int seleccionada = LISTA3.getSelectedIndex();
        String [] parts = ListaPrendas[seleccionada].getFecha().split(" ");
        int DIAS1 = Integer.parseInt(parts[0]);
        int MES1 = Integer.parseInt(parts[1]);
        
        String fecha2 = DIA2.getText()+" "+MES2.getText()+" "+AÑO2.getText();
        String [] parts2 = fecha2.split(" ");
        int DIAS2 = Integer.parseInt(parts2[0]);
        int MES2 = Integer.parseInt(parts2[1]);
        
        int DIASTOTALES=0;
        if(MES2 == MES1){
            DIASTOTALES = DIAS2-DIAS1;
            int diferencia = (30-DIAS1)+DIAS2;
            if(DIASTOTALES > 30){
                for(int i=0;i<= diferencia;i++){
                    prendax.setPagofinal(ListaPrendas[seleccionada].getPrestamo()*.03);
                }
            }
        }
        else if(MES2 != MES1){
            DIASTOTALES = (30-DIAS1)+DIAS2; 
            if(DIASTOTALES > 30){
                int diferencia = DIASTOTALES - 30;
                for(int i=0;i <= diferencia;i++){
                    prendax.setPagofinal(ListaPrendas[seleccionada].getPrestamo()*.03);
                }
            }
            
        }
        REMBOLSO.setText(String.valueOf(prendax.getPagofinal()));
        numeroPrendas++;
    }//GEN-LAST:event_ACTIONCALCULAR

    private void LISTA3SELECTED(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTA3SELECTED
        // TODO add your handling code here:
        int seleccionado = LISTA3.getSelectedIndex();
        String FechaS = DIA2.getText().toString() +"/"+ MES2.getText().toString() + "/"+AÑO2.getText().toString();
        String FechaR = DAY.getText().toString()+"/" + MONTH.getText().toString()+"/"+ YEAR.getText().toString();
        //DUEÑO3.setText(ListaPrendas[seleccionado].getDueño().getNombre());
        //PRESTADO3.setText(Double.toString(ListaPrendas[seleccionado].getPrestamo()));
        REGISTRO3.setText(ListaPrendas[seleccionado].getFecha());
        DUEÑO3.setText(newcliente[seleccionado].getNombre());
        String prest = String.valueOf(ListaPrendas[seleccionado].getPrestamo());
        PRESTADO3.setText(prest);
    }//GEN-LAST:event_LISTA3SELECTED

    private void PRESTADO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESTADO3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PRESTADO3ActionPerformed

    private void LISTA2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTA2
        // TODO add your handling code here:
        int seleccionado = LISTA2.getSelectedIndex();
        //String FechaR = DAY.getText().toString()+"/" + MONTH.getText().toString()+"/"+ YEAR.getText().toString();

        PRENDA.setText(ListaPrendas[seleccionado].getPrenda());
        String [] parts =  ListaPrendas[seleccionado].getFecha().split(" ");
        DAY.setText(parts[0]);
        MONTH.setText(parts[1]);
        YEAR.setText(parts[2]);
        VALUATE.setText(String.valueOf(ListaPrendas[seleccionado].getValorComercial()));
        PRESTAMO.setText(String.valueOf(ListaPrendas[seleccionado].getPrestamo()));
        if(ListaPrendas[seleccionado].getCategoria()=="JOYERIA"){
            CATEGORIA.setSelectedIndex(0);
        }
        else if(ListaPrendas[seleccionado].getCategoria()=="ELECTRONICO"){
            CATEGORIA.setSelectedIndex(1);
        }
        else if(ListaPrendas[seleccionado].getCategoria()=="ELECTRODOMESTICO"){
            CATEGORIA.setSelectedIndex(2);
        }
        else if(ListaPrendas[seleccionado].getCategoria()=="JUGUETE"){
            CATEGORIA.setSelectedIndex(3);
        }
        else if(ListaPrendas[seleccionado].getCategoria()=="MUEBLE"){
            CATEGORIA.setSelectedIndex(4);
        }
    }//GEN-LAST:event_LISTA2

    private void PHONENUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHONENUMActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_PHONENUMActionPerformed

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed
    
    //PARA EL REGISTRO
    CasaEmpeño num;
    private cliente newcliente[];
    private int numClientesIngresados;
    private DefaultListModel model;
    
    //PARA SEGUNDA PESTAÑA
    ComboBoxModel modeloCategoria;
    private int numPrendas;
    private Prenda ListaPrendas[];
    private DefaultListModel prendasemp;
    
    //PARA TERCERA PESTAÑA
    ComboBoxModel PrendasEmpeñadas;
    private String [] listPrendas; 
    private CasaEmpeño prendaguardada[];
    private int numeroPrendas; 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AÑO2;
    private javax.swing.JButton BOTONREGISTRO;
    private javax.swing.JButton BOTTONPRENDA;
    private javax.swing.JToggleButton CALCULAR;
    private javax.swing.JComboBox<String> CATEGORIA;
    private javax.swing.JTextField DAY;
    private javax.swing.JTextField DIA2;
    private javax.swing.JTextField DUEÑO3;
    private javax.swing.JList<String> LISTA2;
    private javax.swing.JList<String> LISTA3;
    private javax.swing.JTextField MES2;
    private javax.swing.JTextField MONTH;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PAGOFINAL;
    private javax.swing.JTextField PHONENUM;
    private javax.swing.JTextField PRENDA;
    private javax.swing.JTextField PRESTADO3;
    private javax.swing.JTextField PRESTAMO;
    private javax.swing.JTextField REGISTRO3;
    private javax.swing.JTextField REMBOLSO;
    private javax.swing.JTextField RESIDUE;
    private javax.swing.JTextField VALUATE;
    private javax.swing.JTextField YEAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
